### ISSUE TITLE
How to use with i2c displays

### ISSUE THREAD

**Issue by WouterrV** [jgOhYeah/LCDGraph#1]
Awesome library! But all my 44780 displays have an i2c connection, and the LiquidCrystal library used by LCDGraph doesn't support i2c displays.

Is there any way of getting LCDGraph to work with i2c lcds?

**Comment by jgOhYeah** [comment]
Hi @WouterrV,
I've just created a new release that should allow templates to be used to specify the library. This will appear in the library manager in a day or so if you are using that, otherwise immediately here on github.

I'm not sure what library you are using for driving the display, but I have been testing with [`LiquidCrystal_I2C`](https://github.com/johnrickman/LiquidCrystal_I2C). Others should work if they are close enough.

See the [I2CDisplay example](https://github.com/jgOhYeah/LCDGraph/blob/main/examples/I2CDisplay/I2CDisplay.ino) for getting started.

Hope this is useful

**Comment by WouterrV** [comment]
Thanks so much!! It worked flawlessy, now my co2 meters have a graph. I tried to make the graph bigger (more lcd-object instances and then splitting the data) but that didn't work out, also the character spacing of a 1602 display makes it not ideal for graphs, but it's a good way to get some insight of the data over time.

![co2 display with graph](https://i.imgur.com/ruAzAHk.jpg)

**Comment by jgOhYeah** [comment]
Good to hear it works and your project is progressing. I agree that these character LCDs aren't ideal for graph displays, but it is good they have some custom character functionality, even if limited.

In terms of graph sizing, these character LCDs can only draw 8 unique custom characters on screen at any one time due to the internal architecture / memory mapping of the control chip, so each `LCDGraph` instance (and any other code using custom characters) must share these between them. This means the 1 row, 8 char wide graph in your photo is as big as the display can cope with unfortunately.
